version: "3"
services:
  backend-factura:
    image: bncc111/backend-factura
    container_name: backend-factura
    build:
      context: https://SmartByt3r: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@github.com/Wolfant/prueba-automatizacion-back.git#main
      dockerfile: Dockerfile
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    networks:
      - netnpx

  react-factura:
    image: bncc111/react-factura
    container_name: react-factura
    build:
      context: https://SmartByt3r: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@github.com/Wolfant/prueba-automatizacion-front.git#main
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - netnpx

volumes:
  db-data:

networks:
  netnpx:
    driver: bridge
