version: "3"
services:
  backend-factura:
    image: bncc111/backend-prueba2-factura
    container_name: backend-factura
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    networks:
      - netnpx

  react-factura:
    image: bncc111/react-prueba2-factura
    container_name: react-factura
    ports:
      - "80:80"
    networks:
      - netnpx

volumes:
  db-data:

networks:
  netnpx:
    driver: bridge
