
name: Backend Test 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install and Test
      run: |
        cd ./backend 
        npm i
        npm test
  build:
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/backend-prueba2-factura:latest
        file: ./backend/Dockerfile