
name: Backend Test 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install and Test
      run: |
        cd ./backend 
        npm i
        npm test
  call-workflow-1-in-local-repo:
    uses: UpsStudents/prueba2-automatizacion/.github/docker-publish.yml@main
    with:
      config-path: "./backend/"
      image-name: "backend-prueba2-factura"
      secrets: inherit