name: Deploy Image Workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      image-name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{inputs.config-path}}
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{inputs.image-name}}:latest
        file: Dockerfile